security:
    encoders:
        FOS\UserBundle\Model\UserInterface: auto
    role_hierarchy:
        ROLE_TIER:        ROLE_USER
        ROLE_OPERATEUR:   ROLE_TIER
        ROLE_ADMIN:       ROLE_OPERATEUR
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: security.user_checker

            logout:       true
            anonymous:    true

    access_control:



        #- { path: ^/, role: ROLE_USER }

