<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrKBngg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrKBngg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXrKBngg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXrKBngg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXrKBngg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XrKBngg',
    'container.build_id' => '6c9b65f0',
    'container.build_time' => 1610559023,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrKBngg');
