<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'Symfony.Component.Form.Form' => 0,
'IteratorAggregate' => 1,
'Symfony.Component.Form.FormInterface' => 2,
'Symfony.Component.Form.ClearableErrorsInterface' => 3,
'Traversable' => 4,
'Countable' => 5,
'ArrayAccess' => 6,
'FOS.UserBundle.Model.User' => 7,
'FOS.UserBundle.Model.UserInterface' => 8,
'FOS.UserBundle.Model.GroupableInterface' => 9,
'Symfony.Component.Security.Core.User.UserInterface' => 10,
'Serializable' => 11,
'Symfony.Component.Security.Core.User.AdvancedUserInterface' => 12,
'FOS.UserBundle.Model.Group' => 13,
'FOS.UserBundle.Model.GroupInterface' => 14,

], [

0 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            clone (\Symfony\Component\VarExporter\Internal\Registry::$prototypes['Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Form\\Extension\\Validator\\Constraints\\Form')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\Form',
                ],
                'defaultGroup' => [
                    'Form',
                ],
                'traversalStrategy' => [
                    2,
                ],
                'constraints' => [
                    [
                        $o[1],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Default' => [
                            $o[1],
                        ],
                        'Form' => [
                            $o[1],
                        ],
                    ],
                ],
                'groups' => [
                    1 => [
                        'Default',
                        'Form',
                    ],
                ],
            ],
        ],
        $o[0],
        []
    );
},
1 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'IteratorAggregate',
                ],
                'defaultGroup' => [
                    'IteratorAggregate',
                ],
            ],
        ],
        $o[0],
        []
    );
},
2 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\FormInterface',
                ],
                'defaultGroup' => [
                    'FormInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
3 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Form\\ClearableErrorsInterface',
                ],
                'defaultGroup' => [
                    'ClearableErrorsInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
4 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Traversable',
                ],
                'defaultGroup' => [
                    'Traversable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
5 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Countable',
                ],
                'defaultGroup' => [
                    'Countable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
6 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'ArrayAccess',
                ],
                'defaultGroup' => [
                    'ArrayAccess',
                ],
            ],
        ],
        $o[0],
        []
    );
},
7 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Length'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Length')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\Length'],
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Email'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Email')),
            $f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'](),
            clone $p['Symfony\\Component\\Validator\\Constraints\\NotBlank'],
            clone $p['Symfony\\Component\\Validator\\Constraints\\Length'],
            clone ($p['Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity')),
            clone $p['Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity'],
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'FOS\\UserBundle\\Model\\User',
                    'username',
                    4 => 'email',
                    8 => 'plainPassword',
                ],
                'defaultGroup' => [
                    'User',
                ],
                'members' => [
                    [
                        'username' => [
                            $o[1],
                        ],
                        'email' => [
                            $o[4],
                        ],
                        'plainPassword' => [
                            $o[8],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'username' => $o[1],
                        'email' => $o[4],
                        'plainPassword' => $o[8],
                    ],
                ],
                'constraints' => [
                    [
                        $o[11],
                        $o[12],
                    ],
                    [
                        $o[2],
                        $o[3],
                    ],
                    4 => [
                        $o[5],
                        $o[6],
                        $o[7],
                    ],
                    8 => [
                        $o[9],
                        $o[10],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Registration' => [
                            $o[11],
                            $o[12],
                        ],
                        'Profile' => [
                            $o[11],
                            $o[12],
                        ],
                    ],
                    [
                        'Registration' => [
                            $o[2],
                            $o[3],
                        ],
                        'Profile' => [
                            $o[2],
                            $o[3],
                        ],
                    ],
                    4 => [
                        'Registration' => [
                            $o[5],
                            $o[6],
                            $o[7],
                        ],
                        'Profile' => [
                            $o[5],
                            $o[6],
                            $o[7],
                        ],
                    ],
                    8 => [
                        'Registration' => [
                            $o[9],
                            $o[10],
                        ],
                        'ResetPassword' => [
                            $o[9],
                            $o[10],
                        ],
                        'ChangePassword' => [
                            $o[9],
                            $o[10],
                        ],
                        'Profile' => [
                            $o[10],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'FOS\\UserBundle\\Model\\User',
                    4 => 'FOS\\UserBundle\\Model\\User',
                    8 => 'FOS\\UserBundle\\Model\\User',
                ],
                'property' => [
                    1 => 'username',
                    4 => 'email',
                    8 => 'plainPassword',
                ],
                'message' => [
                    2 => 'fos_user.username.blank',
                    5 => 'fos_user.email.blank',
                    7 => 'fos_user.email.invalid',
                    9 => 'fos_user.password.blank',
                    11 => 'fos_user.username.already_used',
                    'fos_user.email.already_used',
                ],
                'groups' => [
                    2 => [
                        'Registration',
                        'Profile',
                    ],
                    [
                        'Registration',
                        'Profile',
                    ],
                    5 => [
                        'Registration',
                        'Profile',
                    ],
                    [
                        'Registration',
                        'Profile',
                    ],
                    [
                        'Registration',
                        'Profile',
                    ],
                    9 => [
                        'Registration',
                        'ResetPassword',
                        'ChangePassword',
                    ],
                    [
                        'Registration',
                        'Profile',
                        'ResetPassword',
                        'ChangePassword',
                    ],
                    [
                        'Registration',
                        'Profile',
                    ],
                    [
                        'Registration',
                        'Profile',
                    ],
                ],
                'maxMessage' => [
                    3 => 'fos_user.username.long',
                    6 => 'fos_user.email.long',
                ],
                'minMessage' => [
                    3 => 'fos_user.username.short',
                    6 => 'fos_user.email.short',
                    10 => 'fos_user.password.short',
                ],
                'max' => [
                    3 => 180,
                    6 => 180,
                    10 => 4096,
                ],
                'min' => [
                    3 => 2,
                    6 => 2,
                    10 => 2,
                ],
                'allowEmptyString' => [
                    3 => false,
                    6 => false,
                ],
                'fields' => [
                    11 => 'usernameCanonical',
                    'emailCanonical',
                ],
                'errorPath' => [
                    11 => 'username',
                    'email',
                ],
            ],
        ],
        $o[0],
        []
    );
},
8 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'FOS\\UserBundle\\Model\\UserInterface',
                ],
                'defaultGroup' => [
                    'UserInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
9 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'FOS\\UserBundle\\Model\\GroupableInterface',
                ],
                'defaultGroup' => [
                    'GroupableInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
10 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Security\\Core\\User\\UserInterface',
                ],
                'defaultGroup' => [
                    'UserInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
11 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Serializable',
                ],
                'defaultGroup' => [
                    'Serializable',
                ],
            ],
        ],
        $o[0],
        []
    );
},
12 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'Symfony\\Component\\Security\\Core\\User\\AdvancedUserInterface',
                ],
                'defaultGroup' => [
                    'AdvancedUserInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},
13 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (($f = &\Symfony\Component\VarExporter\Internal\Registry::$factories)['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
            ($f['Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\PropertyMetadata'))(),
            clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Symfony\\Component\\Validator\\Constraints\\NotBlank'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\NotBlank')),
            clone ($p['Symfony\\Component\\Validator\\Constraints\\Length'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Component\\Validator\\Constraints\\Length')),
            clone ($p['Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Symfony\\Bridge\\Doctrine\\Validator\\Constraints\\UniqueEntity')),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'FOS\\UserBundle\\Model\\Group',
                    'name',
                ],
                'defaultGroup' => [
                    'Group',
                ],
                'members' => [
                    [
                        'name' => [
                            $o[1],
                        ],
                    ],
                ],
                'properties' => [
                    [
                        'name' => $o[1],
                    ],
                ],
                'constraints' => [
                    [
                        $o[4],
                    ],
                    [
                        $o[2],
                        $o[3],
                    ],
                ],
                'constraintsByGroup' => [
                    [
                        'Registration' => [
                            $o[4],
                        ],
                    ],
                    [
                        'Registration' => [
                            $o[2],
                            $o[3],
                        ],
                    ],
                ],
                'class' => [
                    1 => 'FOS\\UserBundle\\Model\\Group',
                ],
                'property' => [
                    1 => 'name',
                ],
                'message' => [
                    2 => 'fos_user.group.blank',
                    4 => 'fos_group.name.already_used',
                ],
                'groups' => [
                    2 => [
                        'Registration',
                    ],
                    [
                        'Registration',
                    ],
                    [
                        'Registration',
                    ],
                ],
                'maxMessage' => [
                    3 => 'fos_user.group.long',
                ],
                'minMessage' => [
                    3 => 'fos_user.group.short',
                ],
                'max' => [
                    3 => 180,
                ],
                'min' => [
                    3 => 2,
                ],
                'allowEmptyString' => [
                    3 => false,
                ],
                'fields' => [
                    4 => 'name',
                ],
                'errorPath' => [
                    4 => 'name',
                ],
            ],
        ],
        $o[0],
        []
    );
},
14 => static function () {
    return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
        $o = [
            (\Symfony\Component\VarExporter\Internal\Registry::$factories['Symfony\\Component\\Validator\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::f('Symfony\\Component\\Validator\\Mapping\\ClassMetadata'))(),
        ],
        null,
        [
            'stdClass' => [
                'name' => [
                    'FOS\\UserBundle\\Model\\GroupInterface',
                ],
                'defaultGroup' => [
                    'GroupInterface',
                ],
            ],
        ],
        $o[0],
        []
    );
},

]];
